'use strict';

const { ensureIdempotentIndexing } = require('./_index-utils');

const path = require('path');

function cloneAttribute(attribute) {
  const cloned = { ...attribute };
  delete cloned.Model;
  delete cloned.fieldName;
  delete cloned.field;
  delete cloned.references;
  delete cloned.onDelete;
  delete cloned.onUpdate;
  delete cloned._modelAttribute;
  delete cloned._autoGenerated;
  return cloned;
}

module.exports = {
  async up(queryInterface, Sequelize) {
    ensureIdempotentIndexing(queryInterface);
    const models = require(path.resolve(__dirname, '..', 'src', 'models'));
    const model = models.HotDeal;

    const attrs = {};
    for (const [attributeName, attribute] of Object.entries(model.rawAttributes)) {
      if (attribute?.type?.key === 'VIRTUAL' || attributeName === 'image') {
        continue;
      }

      const columnName = attribute.field || attributeName;
      attrs[columnName] = cloneAttribute(attribute);
    }

    await queryInterface.createTable(model.tableName, attrs);

    await queryInterface.addIndex(model.tableName, ['tenant_id'], {
      name: 'idx_hot_deals_tenant_id'
    }).catch(() => {});
    await queryInterface.addIndex(model.tableName, ['service_id'], {
      name: 'idx_hot_deals_service_id'
    }).catch(() => {});
    await queryInterface.addIndex(model.tableName, ['status'], {
      name: 'idx_hot_deals_status'
    }).catch(() => {});
    await queryInterface.addIndex(model.tableName, ['valid_from', 'valid_until'], {
      name: 'idx_hot_deals_valid_window'
    }).catch(() => {});
  },

  async down(queryInterface) {
    await queryInterface.dropTable('hot_deals');
  }
};
