'use strict';

const { ensureIdempotentIndexing } = require('./_index-utils');

const path = require('path');

function cloneAttribute(attribute) {
  const cloned = { ...attribute };
  delete cloned.Model;
  delete cloned.fieldName;
  delete cloned.field;
  delete cloned.references;
  delete cloned.onDelete;
  delete cloned.onUpdate;
  delete cloned._modelAttribute;
  delete cloned._autoGenerated;
  return cloned;
}

module.exports = {
  async up(queryInterface, Sequelize) {
    ensureIdempotentIndexing(queryInterface);
    const models = require(path.resolve(__dirname, '..', 'src', 'models'));
    const model = models.PaymentTransaction;

    const attrs = {};
    for (const [attributeName, attribute] of Object.entries(model.rawAttributes)) {
      if (attribute?.type?.key === 'VIRTUAL') {
        continue;
      }

      const columnName = attribute.field || attributeName;
      attrs[columnName] = cloneAttribute(attribute);
    }

    await queryInterface.createTable(model.tableName, attrs);

    await queryInterface.addIndex(model.tableName, ['appointment_id'], {
      name: 'idx_payment_transactions_appointment'
    }).catch(() => {});
    await queryInterface.addIndex(model.tableName, ['order_id'], {
      name: 'idx_payment_transactions_order'
    }).catch(() => {});
    await queryInterface.addIndex(model.tableName, ['type'], {
      name: 'idx_payment_transactions_type'
    }).catch(() => {});
    await queryInterface.addIndex(model.tableName, ['status'], {
      name: 'idx_payment_transactions_status'
    }).catch(() => {});
    await queryInterface.addIndex(model.tableName, ['processed_at'], {
      name: 'idx_payment_transactions_processed_at'
    }).catch(() => {});
  },

  async down(queryInterface) {
    await queryInterface.dropTable('payment_transactions');
  }
};
